 platform :ios, ‘8.0’

target 'TT' do

  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod "AFNetworking"
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'Masonry'
  pod 'SDCycleScrollView'
  pod 'YYKit'
   pod 'SVProgressHUD'


  target 'TTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TTUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
